import { PROFILE_BACKGROUND_SWEEP_LIMIT } from "../profileBackgroundLimits.ts";
export {
  infrastructureRetryDelaySeconds as profileGameProjectionRetryDelaySeconds,
  MAX_INFRASTRUCTURE_RETRY_DELAY_SECONDS as MAX_PROFILE_GAME_PROJECTION_RETRY_DELAY_SECONDS,
} from "../queueRetry.ts";

export const PROFILE_GAME_PROJECTION_SWEEP_LIMIT =
  PROFILE_BACKGROUND_SWEEP_LIMIT;
export const PROFILE_GAME_PROJECTION_SWEEP_CONCURRENCY = 10;
export const PROFILE_GAME_PROJECTION_RECOVERY_DELAY_MS = 5 * 60 * 1_000;
export const HISTORICAL_MATCH_ARCHIVE_BATCH_SIZE = 5;
